# fly.toml app configuration file generated for karaoke-room on 2026-08-27T01:03:32Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'karaoke-room'
primary_region = 'sjc'

[build]

[env]
  CLIENT_ORIGIN = 'https://karaoke-room.fly.dev'
  NODE_ENV = 'production'
  PORT = '8080'
  TRUST_PROXY = '1'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 250
    soft_limit = 200

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
